server:
  port: 8081

spring:
  application:
    name: Produit-MS

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
    instance:
      lease-renewal-interval-in-seconds: 30
      lease-expiration-duration-in-seconds: 90
      prefer-ip-address: true

spring.cloud.config.uri: http://localhost:8888
spring.cloud.config.import-check.enabled: false
